### ISSUE TITLE
Mod causes a crash when loaded on a dedicated server

### ISSUE THREAD

**Issue by BeamerPi** [shmove/cat_jam#10]
I am attempting to use the cat_jam mod on a forge modded server I host (v.1.20.1) and the cat_jam mod fails to load. It loads fine in my single player modded forge setup, so I suspect there is something about the server side of things having issues, the error messages seem to support this (given that the errors seem to contain the word "client" and "invalid dist DEDICATED_SERVER"). If I understood more about programming I'd probably be able to give better info, thank you for your time and effort, because I get that this is something you do in your free time and for the love of the game, so I don't take you for granted.

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:1.0] {}
-- MOD cat_jam --
Details:
	Mod File: /C:/Users/beame/AppData/Roaming/.minecraft1.20.1-forge/mods/cat_jam-forge-mc1.20-1.2.1.jar
	Failure message: cat_jam (cat_jam) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
	Mod Version: 1.2.1
	Mod Issue URL: https://github.com/shmove/cat_jam/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER

**Comment by shmove** [comment]
it might be an error on my part that it attempts to load on serverside at all and i'll have a look into that, but this mod is intended to be used clientside **exclusively**! those on the server should have the mod installed on their client to see their cats jam, but the server itself does not need the mod. hope this helps!

**Comment by BeamerPi** [comment]
Ah, thank you, I'll pull it from the server for the nonce.

**Comment by shmove** [comment]
Forge [doesn't seem to have a sidedness attribute](https://docs.minecraftforge.net/en/latest/concepts/sides/#writing-one-sided-mods), so I'm just going to mark this as `wontfix` and let the crash serve as a reminder that the mod would have no functionality on the server regardless.
