### ISSUE TITLE
Cat jam compat with fat cat resourcepack?

### ISSUE THREAD

**Issue by Kloytz** [shmove/cat_jam#12]
Will cat jam get compat with fat cat resourcepack?

**Comment by shmove** [comment]
Are you referring to [this one](https://modrinth.com/resourcepack/fat-cats-java)? Similar to #1, this relies on compatibility with Entity Model Features which is not currently implemented. I will continue to look into it when I can.

**Comment by Kloytz** [comment]
https://modrinth.com/resourcepack/fat-cat
Was talking about this one, but similar to the other resource pack it also uses emf.
