### ISSUE TITLE
[Suggestion] Custom segment through ressource packs

### ISSUE THREAD

**Issue by MidyGamy** [shmove/cat_jam#4]
So if we have custom music discs, we can have accurate cat dancing not offsync (and maybe add other mods/datapack support?)

**Comment by shmove** [comment]
I'd love to work on supporting various modded discs and will try and do that soon :) However I don't think it's too feasible to support custom routines for resource pack discs unfortunately and don't intend on working on that

**Comment by MidyGamy** [comment]
I can try to help
