### ISSUE TITLE
Newly Tamed Cats do not jam to the music if in the range of a jukebox until the disc is taken out and placed back in.

### ISSUE THREAD

**Issue by TremendousTourmaline** [shmove/cat_jam#5]
Steps to reproduce:
1. Spawn several cats and tame them.
2. Place a jukebox and place a music disc in it. The already tamed cats should start jamming.
3. Spawn a new cat and then tame it.
4. Take note as to whether it starts jamming or not.

EXPECTATION:
The newly-tamed cat should start jamming.

OBSERVATION:
The cat does not bop its head.

**Comment by shmove** [comment]
I don't consider this a bug, as it matches the behaviour of Parrots in the same scenario.

![](https://i.imgur.com/HpoaEiB.gif)

However, Allays _do_ start to dance if brought/summoned within range of a jukebox while it is already playing. The way disc playback is currently handled would make it very difficult to start a cat jamming in the middle of a song, but I plan to change this in the future. When I do, I'll look into possibly making this behaviour match the Allays.

**Comment by TremendousTourmaline** [comment]
I should've taken parrots into account! Whoops. :P

**Comment by shmove** [comment]
This is now implemented as of v1.2.0 which will be released alongside the update to Minecraft 1.20.2 <3
