### ISSUE TITLE
Mod breaks Simple Voice Chat

### ISSUE THREAD

**Issue by henkelmax** [shmove/cat_jam#6]
Your `ALSpeakerBaseMixin` will create a  null pointer exception, as `category` is `@Nullable`:
https://github.com/shmove/cat_jam/blob/fc937dfde24a83dcaae0b789c5db3a2f44992bac/fabric/src/main/java/com/shmove/cat_jam/fabric/mixin/compat/audioplayer/ALSpeakerBaseMixin.java#L16-L21

https://github.com/henkelmax/simple-voice-chat/blob/acf3380d7b02775d3c29dd39c5977801b1a64478/common/src/main/java/de/maxhenkel/voicechat/voice/client/speaker/ALSpeakerBase.java#L79

It is strongly discouraged to directly mixin into the voice chat mod, as this will break if the mods code changes.
This should be done with the [API](https://modrepo.de/minecraft/voicechat/api/overview), as it does not break across mod versions.

EDIT: This event should work: https://voicechat.modrepo.de/de/maxhenkel/voicechat/api/events/OpenALSoundEvent.Pre.html

**Comment by shmove** [comment]
I apologise for this, I've removed the offending versions for download and will fix this as soon as I can.

**Comment by shmove** [comment]
I have released a new mod version with this fix.
