### ISSUE TITLE
...

### ISSUE THREAD

**Issue by suerion** [shmove/cat_jam#7]

**Comment by shmove** [comment]
While I appreciate the concern, that mod is a port of an older mod (which existed before cat_jam) for Forge with the same functionality. cat_jam does not attempt to copy this functionality despite having a similar concept, and once I realised this mod had a similar concept I got in touch with the original creator before starting work here. cat_jam offers unique animations per disc as opposed to Cat Jammies uniform animation.

**Comment by suerion** [comment]
no problem, i had seen the infos
